### PR TITLE
Update message from 'create' to "*" for attributes in placement instances

### PR DESCRIPTION
**Pull request by A-Beck**
Need to update message to '*' for attributes, since the default instance will always be invoked with a message of the provider name.
This means that the attributes will never be initialized with the default of 'create'

### CODE REVIEW

**Comment by itewk** [comment]
@A-Beck why this change? that `create` message comes from the instance in `ManageIQ` this was copied from, so it would seem an odd change to have to make.

**Comment by A-Beck** [comment]
@itewk this is just lived experience here when I was trying to set storage percentages. The attribute was not being set in $evm.object until I updated to create to '*'. I agree that it is odd change to have to make.

I'll do some more research and come back, or close this PR.

**Comment by A-Beck** [comment]
Closing this, because I could not find good info about the intended purpose of those fields.

**Comment by jeffwarnica** [comment]
@A-Beck the fields are documented in my file https://github.com/RedHatOfficial/miq-Utilities/pull/144/files#diff-8f9cbd18de5d0417655e1512b3150a37 in PR#144. But that PR does imply moving the configuration from "instance variables" to settings.rb, though instance variables would still be allowed.

**Pull request closed without merging**
